language: objective-c
script:
  - df -h /
  - uname -a
  - xcodebuild -version
  - system_profiler SPHardwareDataType

matrix:
  include:
  - os: osx
    osx_image: beta-xcode6.1
  - os: osx
    osx_image: beta-xcode6.2
  - os: osx
    osx_image: xcode6.4
  - os: osx
    osx_image: xcode7
  - os: osx
    osx_image: xcode7.1
  - os: osx
    osx_image: xcode7.2
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8
